### ISSUE TITLE
Confusing new variable initialization in the Expr.lama

### ISSUE THREAD

**Issue by e2e4b6b7** [danyaberezun/compilers-supplementary#1424]
[Here](https://github.com/danyaberezun/compilers-supplementary/blob/8e2de0105b3366834368ebfa2049223681d2efb9/src/Expr.lama#L82) (And I guess in later tasks)
Statement: 
```foldl (fun (s, name) {s.addName (name, Var (0))}, state, names)``` 
is confusing because to actually initialize a new value with 0 we have to write:
```foldl (fun (s, name) {s.addName (name, 0)}, state, names)```
The reason why it was not a problem is that we do not have access to the uninitialized variable in the tests. But nevertheless I guess we should rewrite it into the correct initialization with 0 or:
```foldl (fun (s, name) {s.addName (name, Uninitialized)}, state, names)```

**Comment by danyaberezun** [comment]
Not a bug. It should never be a number, it should be either `Var(<value>)` or `Fun (<fun_value>)`
